function [X,Y] =evol_boundary_mitosis(x1,y1,N0,Ts)
% x1 and y1 contain the coordinates of the boundary generated by the contour
% Following algorithm. 

% N0=20; %No.of bodies
%Ts=100; %time steps
dt=0.1; %[s]
R0=1e-6;%0.05; [m]
L0=2e-6;

eta=.01; %[Pa s]
mu=-4e-11; %[N/m]
dragc=6*pi*eta*R0;
%k=1e-11;
X=zeros(Ts,N0); %X-coord of the N0 bodies at all the time steps
Y=zeros(Ts,N0); %Y-coord of the N0 bodies at all the time steps

eps=1.5e-6;% Boundary safe distance from each particle
kboundary=1e-3; %spring constant of Boundary springs
bdsize=ceil(length(x1)/2); %no. of boundary pts we pick
Bdpts=zeros(2,bdsize);

load('initial.mat');

for i=1:bdsize
Bdpts(:,i)=[x1(2*i-1) ; y1(2*i-1)]; %taking alternate points instead of all.    
end

tempx=x1(round(linspace(1,187,N0)')); % I used inspace instead of the range operator
tempy=y1(round(linspace(1,187,N0)'));
X(1,:)=0.75*tempx; %Now scaling them so that they don't coincide with the boundary pts
Y(1,:)=0.75*tempy; %Now Scaling them so that they don't coincide with the boundary pts

%dx=zeros(N0,N0); % is the difference matrix..contains dx
%dy=zeros(N0,N0); % is the difference matrix..contains dy
%r=zeros(N0,N0);  % is the magnitude matrix..contains sqrt[dx^2 + dy^2]
%--------------------------------------------------------------------------
for k=2:Ts  %for time steps

%Cell Force:    
    xk=X(k-1,1:N0); %Storing X(k-1) into a dummy row vector xk to do the repmat thing
    yk=Y(k-1,1:N0);%Storing Y(k-1) into a dummy row vector yk to do the repmat thing

    dx=repmat(xk,N0,1)'-repmat(xk,N0,1); % this the X1-X2 difference matrix
    dy=repmat(yk,N0,1)'-repmat(yk,N0,1); % this the Y1-Y2 difference matrix
    r=sqrt(dx.^2+dy.^2);

    Fx= mu*sum( (r<4*R0).*dx.*(L0-r)./(r+(r==0)*1),   2);   %Contains the forces Fx on all N0 bodies at the kth time step
    Fy= mu*sum( (r<4*R0).*dy.*(L0-r)./(r+(r==0)*1),   2);   %Contains the forces Fy on all N0s bodies at the kth time step

%------------------------------------
%boundary Force:
    bxk=Bdpts(1,:);
    byk=Bdpts(2,:);

    bdx=repmat(xk,bdsize,1)'-repmat(bxk,N0,1);  % this the Xi-BXj difference matrix
    bdy=repmat(yk,bdsize,1)'-repmat(byk,N0,1);  % this the Yi-BYj difference matrix
    rb=sqrt(bdx.^2+bdy.^2);

    BFx= kboundary*sum( (rb<eps).*bdx ,2);
    BFy= kboundary*sum( (rb<eps).*bdy ,2);
%-----------------------------------                
Inter_time=50; %Interphase time interval LENGTH..constant for all cells
Tstart=10; % time ITERATION at which interface begins...Must be assigned randomly..
m=7;% Right now, mth cell is in mitosis
Fnewcell=zeros(2,N0);

if(k==Tstart+Inter_time) %This block triggers the interphase process..Introduces the new cell
    N=N0+1;
    tmit=0; %tmit indexes the mitosis stage
    X=[X  zeros(Ts,1)]; %adding new column
    Y=[Y  zeros(Ts,1)]; %adding new column    
    X(k,N)= X(k-1,m)+ 1e-7; %giving initial position for new cell
    Y(k,N)= Y(k-1,m)+ 1e-7; %giving initial position for new cell   
end


if ( k-(Tstart+Inter_time)>0) % This block carries the Mitosis process and also computes the force corresponding to the newcell
    tmit=tmit+1;%keeps track of the steps in mitosis
    tcurrent=k; %i.e., current time step
    Fnewcell=mitosis(mu,N,m,X,Y,tcurrent,tmit,Tstart,Inter_time); %Fnewcell gives the forces by the newcell acting on all the other bodies

    X(k,N)=X(k-1,N)-sum(Fnewcell(1,:),2)*dt/dragc+1e-7*sqrt(dt)*randn(1); % '-' comes because of Newton's 3rd law. SInce we need force on newcell from other bodies
    Y(k,N)=Y(k-1,N)-sum(Fnewcell(2,:),2)*dt/dragc +1e-7*sqrt(dt)*randn(1);
end
%-----------------------------------

%Summing for the 1st N0 bodies
    X(k,1:N0)=X(k-1,1:N0)+ Fx'*dt/(dragc)  + BFx(1:N0,1)'+  Fnewcell(1,1:N0)+  1e-7*sqrt(dt)*randn(1,N0);
    Y(k,1:N0)=Y(k-1,1:N0)+ Fy'*dt/(dragc)  + BFy(1:N0,1)'+  Fnewcell(2,1:N0)+  1e-7*sqrt(dt)*randn(1,N0);    
end
%--------------------------------------------------------------------------


% %-----------------------for plotting the
        %randcol=[1 0 1; 1 0 0; 0 1 0; 0 0 0; 0 0 1; 1 1 0];
        %magenta, red, green, black, blue, yellow
         t=-pi:0.01:pi;
           for k=1:Ts
                for i=1:N0
                axis([-8e-6  8e-6  -5e-6  5e-6]);     
                
                if (i==m)
                plot(X(k,i)+R0*cos(t),Y(k,i)+R0*sin(t),'color','red','linewidth',5); hold on
                
                else 
                plot(X(k,i)+R0*cos(t),Y(k,i)+R0*sin(t),'color','black','linewidth',5); hold on
                %centers     plot(X(k,i),Y(k,i),'.','color','black','linewidth',2); hold on 
                end
                
                if ( k-(Tstart+Inter_time)>0)  %&&  k-(Tstart+Inter_time)<=10 &&)
                plot(X(k,N)+R0*cos(t),Y(k,N)+R0*sin(t),'color','blue','linewidth',5); hold on
                end
                
                title(['This is time step: ',num2str(k+1),'/',num2str(Ts)]); hold on
                plot(Bdpts(1,:),Bdpts(2,:),'*'); hold on
                
                grid on; hold on
                end
            pause(0.100);
            hold off
           
           end
%-----------------------for plotting the balls
end
